### ISSUE TITLE
Getting very narrow charts (on WSL)

### ISSUE THREAD

**Issue by arielgabizon** [madnight/bitcoin-chart-cli#18]
![image](https://user-images.githubusercontent.com/5689834/81051567-327bdf80-8ec2-11ea-82d4-5f57a1d58082.png)

**Comment by madnight** [comment]
For all charts or only with this specific parameters?

**Comment by arielgabizon** [comment]
all

**Comment by Emobe** [comment]
I'm getting these on arch linux. I just ran with no parameters

**Comment by madnight** [comment]
yup seems to be a problem with version 3.3.1

3.3.0 works fine

**Comment by madnight** [comment]
Alright fixed it, latest version `npx bitcoin-chart-cli@3.3.3` works again.

The problem was that I always use `yarn` locally and `yarn` uses the `yarn.lock` file with a working set of versions. However, with `npm` you get a new set of versions depending on the versions constrains in the `package.json`. These constrains were to loose and `npm` bundled a set of versions together that did not work. I pinned the versions in `package.json` and also added a `package-lock.json` to freeze the versions for `npm` too.

Thx for the error reporting and patience.

**Comment by arielgabizon** [comment]
Thanks! Works well
